development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000
  session_key: spree_development
  secret: YrDOFOmwwyFg2tTZykCbZjWYQUbKBt

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000
  session_key: spree_test
  secret: Pl8qJNFc8mowyt1xtHOmfUGHOPEutu

# This "session_key" can be any string, and should be unique to your installation (e.g. mysite_session)
# This "secret" must be a random string, at least 30 characters long, and kept secret for security

#   The production section modified to support configuration automation at Slicehost
#   The secret and password fields should be updated for any externally facing or production use
production:
  adapter: mysql
  database: spree_production
  username: root
  password: 
  host: localhost
  session_key: spree_production
  secret: RSTRebtQwqDy4tgFooSw4Al3xHau4FErig 

import:
  adapter: mysql
  database: punbb
  username: root
  password: 
  host: localhost
  prefix: pun_
